apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymenttest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
          - name: webapp
            image: sirfragalot/docker-demo:dcus
            ports:
              - containerPort: 8080
---

apiVersion: apps/v1
kind: apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
    app: webapp
  ports:
  - protocol: TCP
    port: 8080
  type: NodePort
