apiVersion: apps/v1
kind: DeploymentTest
metadata:
  name: mydeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
          - name: webapp
            image: sirfragalot/docker-demo:dcus
            ports:
              - containerPort: 8080