apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: webapp
      image: sirfragalot/docker-demo:dcus
      ports:
       - containerPort: 80

---

apiVersion: v1
kind: Pod
metadata:
  name: pod1-label
  labels:
    app: webapp
spec:
  containers:
    - name: web
      image: sirfragalot/docker-demo:dcus
      ports:
       - containerPort: 80